In [1]:
import pandas as pd

In [2]:
data = {
    "yas": [22, 27, 31, 24, 29],
    "sehir": ["Bursa", "Istanbul", "Ankara", "Bursa", "Istanbul"],
    "maas": [25000, 41000, 52000, None, 46000]
}

df = pd.DataFrame(data)

In [3]:
df

   yas     sehir     maas
0   22     Bursa  25000.0
1   27  Istanbul  41000.0
2   31    Ankara  52000.0
3   24     Bursa      NaN
4   29  Istanbul  46000.0

In [4]:
df.shape

(5, 3)

In [5]:
boyut = df.shape

boyut

(5, 3)

In [6]:
boyut[0]

5

In [7]:
df["yas"]

0    22
1    27
2    31
3    24
4    29
Name: yas, dtype: int64

In [8]:
df["maas"]

0    25000.0
1    41000.0
2    52000.0
3        NaN
4    46000.0
Name: maas, dtype: float64

In [9]:
df["sehir"]

0       Bursa
1    Istanbul
2      Ankara
3       Bursa
4    Istanbul
Name: sehir, dtype: str

In [10]:
numeric_df = df.select_dtypes(include="number")

numeric_df

   yas     maas
0   22  25000.0
1   27  41000.0
2   31  52000.0
3   24      NaN
4   29  46000.0

In [11]:
numeric_count = numeric_df.shape[1]

numeric_count

2

In [12]:
categorical_df = df.select_dtypes(exclude="number")

categorical_df

      sehir
0     Bursa
1  Istanbul
2    Ankara
3     Bursa
4  Istanbul

In [13]:
categorical_count = categorical_df.shape[1]

categorical_count

1

In [17]:
numeric_ratio = numeric_count / column_count

numeric_ratio

0.6666666666666666

In [16]:
row_count = df.shape[0]
column_count = df.shape[1]

print("Satır sayısı:", row_count)
print("Sütun sayısı:", column_count)

Satır sayısı: 5
Sütun sayısı: 3

In [18]:
categorical_df = df.select_dtypes(exclude="number")

categorical_df

      sehir
0     Bursa
1  Istanbul
2    Ankara
3     Bursa
4  Istanbul

In [19]:
categorical_count = categorical_df.shape[1]

categorical_count

1

In [20]:
categorical_ratio = categorical_count / column_count

categorical_ratio

0.3333333333333333

In [21]:
print("DATA DNA - Temel Profil")
print("-----------------------")
print("Satır sayısı:", row_count)
print("Sütun sayısı:", column_count)
print("Sayısal sütun sayısı:", numeric_count)
print("Kategorik sütun sayısı:", categorical_count)
print("Sayısal sütun oranı:", numeric_ratio)
print("Kategorik sütun oranı:", categorical_ratio)

DATA DNA - Temel Profil
-----------------------
Satır sayısı: 5
Sütun sayısı: 3
Sayısal sütun sayısı: 2
Kategorik sütun sayısı: 1
Sayısal sütun oranı: 0.6666666666666666
Kategorik sütun oranı: 0.3333333333333333

In [22]:
df.isna()

     yas  sehir   maas
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False   True
4  False  False  False

In [23]:
df.isna().sum()

yas      0
sehir    0
maas     1
dtype: int64

In [24]:
missing_count = df.isna().sum().sum()

missing_count

np.int64(1)

In [25]:
total_cells = row_count * column_count

total_cells

15

In [27]:
missing_ratio = missing_count / total_cells

missing_ratio

np.float64(0.06666666666666667)

In [28]:
type(missing_count)

numpy.int64

In [29]:
normal_sayi = 1

In [30]:
type(normal_sayi)

int

In [31]:
type(missing_count)

numpy.int64

In [32]:
missing_count

np.int64(1)

In [33]:
print(missing_count)

1

In [34]:
missing_percentage = missing_ratio * 100
round(missing_percentage, 2)

np.float64(6.67)

In [35]:
print("Eksik veri oranı: %", round(missing_percentage, 2))

Eksik veri oranı: % 6.67

In [36]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [37]:
duplicate_test = pd.DataFrame({
    "yas": [22, 27, 22],
    "sehir": ["Bursa", "Istanbul", "Bursa"],
    "maas": [25000, 41000, 25000]
})

duplicate_test

   yas     sehir   maas
0   22     Bursa  25000
1   27  Istanbul  41000
2   22     Bursa  25000

In [38]:
duplicate_test.duplicated().sum()

np.int64(1)

In [39]:
duplicate_count = df.duplicated().sum()

duplicate_count

np.int64(0)

In [40]:
duplicate_ratio = duplicate_count / row_count

duplicate_ratio

np.float64(0.0)

In [41]:
duplicate_percentage = duplicate_ratio * 100

print("Tekrarlı kayıt oranı: %", round(duplicate_percentage, 2))

Tekrarlı kayıt oranı: % 0.0

In [42]:
outlier_test = pd.DataFrame({
    "maas": [25000, 41000, 46000, 52000, 900000]
})

outlier_test

     maas
0   25000
1   41000
2   46000
3   52000
4  900000

In [43]:
Q1 = outlier_test["maas"].quantile(0.25)

Q1

np.float64(41000.0)

In [44]:
Q3 = outlier_test["maas"].quantile(0.75)

Q3

np.float64(52000.0)

In [45]:
IQR = Q3 - Q1

IQR

np.float64(11000.0)

In [46]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Alt sınır:", lower_bound)
print("Üst sınır:", upper_bound)

Alt sınır: 24500.0
Üst sınır: 68500.0

In [47]:
outlier_test["maas"] > upper_bound

0    False
1    False
2    False
3    False
4     True
Name: maas, dtype: bool

In [48]:
outliers = (
    (outlier_test["maas"] < lower_bound) |
    (outlier_test["maas"] > upper_bound)
)

outliers

0    False
1    False
2    False
3    False
4     True
Name: maas, dtype: bool

In [49]:
outlier_count = outliers.sum()

outlier_count

np.int64(1)

In [50]:
outlier_ratio = outlier_count / len(outlier_test)

outlier_percentage = outlier_ratio * 100

print("Aykırı değer oranı: %", round(outlier_percentage, 2))

Aykırı değer oranı: % 20.0

In [51]:
df["maas"]

0    25000.0
1    41000.0
2    52000.0
3        NaN
4    46000.0
Name: maas, dtype: float64

In [52]:
maas_Q1 = df["maas"].quantile(0.25)
maas_Q3 = df["maas"].quantile(0.75)

print("Q1:", maas_Q1)
print("Q3:", maas_Q3)

Q1: 37000.0
Q3: 47500.0

In [53]:
maas_IQR = maas_Q3 - maas_Q1

maas_IQR

np.float64(10500.0)

In [54]:
maas_lower_bound = maas_Q1 - 1.5 * maas_IQR
maas_upper_bound = maas_Q3 + 1.5 * maas_IQR

print("Alt sınır:", maas_lower_bound)
print("Üst sınır:", maas_upper_bound)

Alt sınır: 21250.0
Üst sınır: 63250.0

In [55]:
maas_outliers = (
    (df["maas"] < maas_lower_bound) |
    (df["maas"] > maas_upper_bound)
)

maas_outliers

0    False
1    False
2    False
3    False
4    False
Name: maas, dtype: bool

In [56]:
for column in numeric_df.columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print("Sütun:", column)
    print("Alt sınır:", lower_bound)
    print("Üst sınır:", upper_bound)
    print("--------------------")

Sütun: yas
Alt sınır: 16.5
Üst sınır: 36.5
--------------------
Sütun: maas
Alt sınır: 21250.0
Üst sınır: 63250.0
--------------------

In [60]:
numeric_df.columns

Index(['yas', 'maas'], dtype='str')

In [61]:
for column in numeric_df.columns:
    print(column)

yas
maas

In [62]:
for column in numeric_df.columns:
    print("Şu anda incelenen sütun:", column)
    print(df[column])
    print("--------------------")

Şu anda incelenen sütun: yas
0    22
1    27
2    31
3    24
4    29
Name: yas, dtype: int64
--------------------
Şu anda incelenen sütun: maas
0    25000.0
1    41000.0
2    52000.0
3        NaN
4    46000.0
Name: maas, dtype: float64
--------------------

In [63]:
for column in numeric_df.columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print("Sütun:", column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Alt sınır:", lower_bound)
    print("Üst sınır:", upper_bound)
    print("------------------------")

Sütun: yas
Q1: 24.0
Q3: 29.0
IQR: 5.0
Alt sınır: 16.5
Üst sınır: 36.5
------------------------
Sütun: maas
Q1: 37000.0
Q3: 47500.0
IQR: 10500.0
Alt sınır: 21250.0
Üst sınır: 63250.0
------------------------